(define (problem sequentialqnp07) (:domain sequentialqnp)
    (:objects v0 v1 v2 v3 v4 v5 v6 v7) ; v0 always 0
    (:init
        (gr0 v1)
        (gr0 v2)
        (gr0 v3)
        (gr0 v4)
        (gr0 v5)
        (gr0 v6)
        (gr0 v7)
        (next v0 v1)
        (next v1 v2)
        (next v2 v3)
        (next v3 v4)
        (next v4 v5)
        (next v5 v6)
        (next v6 v7)
        (p))

    (:goal (not (gr0 v7)))
    (:constraint :a (a v0 v1))
    (:constraint :a (a v1 v2))
    (:constraint :a (a v2 v3))
    (:constraint :a (a v3 v4))
    (:constraint :a (a v4 v5))
    (:constraint :a (a v5 v6))
    (:constraint :a (a v6 v7)))
