PROBLEM = 'Problem'
PREPROCESS = 'Pre-processing time'
MEMORY = 'Memory'
MAXMEM = 'Max Memory'
SAT = 'Sat'
MODELS = 'Models'
CALLS = 'Calls'
TIME = 'Time'
SOLVING = 'Solve Time'
MODEL1st = '1st Model Time'
TIMEUNSAT = 'Unsat Time'
CPUTIME = 'CPU Time'
STATE_N = 'States'
ACTION_N = 'Actions'
STDOUT = 'Stdout'
RESULT = 'Result'

STATUS = 'Status'
TIMEOUT = 'Timeout'
MEMOUT = 'Memory out'
FINISH = 'Finished'

SAT_N = 'Sat count'
UNSAT_N = 'Unsat count'
TIMEOUT_N = 'Timeout count'
MEMOUT_N = 'Memory out count'